version: "3.8"

services: 
  fe-container:
    tty: true
    container_name: fe-container
    build:
      context: .
      dockerfile: react.Dockerfile
    volumes: 
      - './frontend:/opt/app'
    ports: 
      - '8080:8080'
    command: sh -c 'npm run start'

  be-container:
    tty: true
    container_name: be-container
    build:
      context: .
      dockerfile: go.Dockerfile
    volumes: 
      - ./backend:/go/src/app
    ports: 
      - '8000:8000'
    working_dir: /go/src/app
