version: "3.8"

services:
  fe-container:
    tty: true
    container_name: fe-container
    build:
      context: .
      dockerfile: react.Dockerfile
    volumes:
      - '/opt/app/node_modules'
      - './frontend:/opt/app'
    ports:
      - '8080:8080'

  be-container:
    tty: true
    container_name: be-container
    build:
      context: .
      dockerfile: go.Dockerfile
    volumes:
      - ./backend:/go/src/app
    ports:
      - '8000:8000'
    working_dir: /go/src/app

  reng-container:
    tty: true
    container_name: reng-container
    build:
      context: .
      dockerfile: python.Dockerfile
    volumes:
      - './recommender-engine:/opt/app'
    ports:
      - '8040:8040'
    working_dir: /opt/app
    