export type Place = {
    placeId: string,
    placeName: string,
    latitude: number,
    longtitude:number,
    introduction: string,
    detail: string,
    activities: string,
    thaiChildFee: number,
    thaiAdultFee: number,
    foreignChildFee: number,
    foreignAdultFee: number,
    targets: any,
    addressDetail: string,
    subDistrict: string,
    district: string,
    province: string,
    postcode: string,
    telPhones: string,
    mobilePhone: string,
    faxNumber: string,
    email: string,
    urls: string,
    thumbnalUrl: string,
    monday: string,
    tuesday: string,
    wednesday: string,
    thursday: string,
    friday: string,
    saturday: string,
    sunday: string,
    recommendedDuration: number,
    tag1: number,
    tag2: number,
    tag3: number,
    tag4: number,
    tag5: number,
}