name: Automate build and Testing

on:
    pull_request:
        branches:
            - main

defaults:
    run:
        working-directory: frontend

jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 10.x
              uses: actions/setup-node@v1
              with:
                node-version: '10.x'
            
            - run: yarn
            - run: yarn test
            - run: yarn build

